# Contributor - Mostafa Mahtab
# Configuration file for database connection and JPA settings

# Dynamic fallback configuration: Connects to Docker container database by default, 
# but accepts environment variable overrides if provided.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-db:3306/immigrant_db?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}

# Enable Hibernate to update tables cleanly
spring.jpa.hibernate.ddl-auto=update
# it the spring.sql.init.mode = always the data doesn't get saved after stopping the docker or docker-compose down
spring.sql.init.mode=NEVER
spring.jpa.defer-datasource-initialization=true

# Show SQL statements in console logs
spring.jpa.show-sql=true
